# Generated by Django 5.1.3 on 2024-11-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FabricType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип ткани',
                'verbose_name_plural': 'Типы ткани',
            },
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('color', models.CharField(max_length=200, verbose_name='Цвет')),
                ('fabric_type', models.ManyToManyField(to='fabrics_app.fabrictype', verbose_name='Тип ткани')),
            ],
            options={
                'verbose_name': 'Ткань',
                'verbose_name_plural': 'Ткани',
            },
        ),
    ]
